# App configuration
app:
  name: event-collector
  service_mode: server

# Log
logger:
  level: debug  # debug, info, warn, error, dpanic, panic, fatal
  encoding: json # json or console
  development: false
  outputPaths: stdout,logs/app_.log
  errorOutputPaths: stderr,logs/error.log
  disableCaller: true
  disableStacktrace: false
  sampling:
    initial: 100
    thereafter: 100

# Server configuration
server:
  grpc:
    port: 50051
    reflection: true
  http:
    host: ""
    port: 8000

# Database configuration
database:
  uri: "mongodb://mongo:27017/activity-stream-hub"
  migrate:
    path: "./internal/database/mongo/migrations"   # the path to your migration file start with ./
    type: up
    step: 2  # if type is step define the step to forward or backward(negative for backward)

prometheus:
  host: 0.0.0.0
  port: 9999
  url: localhost:9091
  metrics_prefix: message-go
  metrics_suffix: message-go